---
extends: default

rules:
  comments:
    ignore: |
      test/templates/cloud-config.yaml
  document-start:
    ignore: |
      test/templates/runtime-init-config.yaml
  line-length:
    max: 120
    ignore: |
      test/templates/gdm-v2-standalone-config.yaml
